{% set name = "amiga" %}
{% set version = "2.0.3" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/firasmidani/amiga
  git_tag: dev

build:
  script_env:
   - EXCLUDE_FILES="docs/ examples/"
  noarch: python
  number: 0
  entry_points:
    - amiga = amiga.amiga:AMiGA

requirements:
  build:
    - python >=3.12,<3.13
    - setuptools
    - pip

  run:
    - python >=3.12,<3.13
    - cython
    - cycler
    - decorator
    - gpy
    - kiwisolver
    - matplotlib
    - numpy
    - pandas
    - paramz
    - pyparsing
    - python-dateutil
    - pytz
    - scipy
    - seaborn
    - six
    - tabulate

  test:
    imports: 
      - amiga
    commands:
      - python amiga/tests/test_amiga.py

outputs:
  - name: amiga
    files:
      include:
        - README.md
        - LICENSE.md
        - amiga/**
      exclude:
        - docs/**
        - examples/**

about:
  home: https://github.com/firasmidani/amiga
  summary: "Analysis of Microbial Growth Assays"
  license: GNU GPL v3.0
  license_file: LICENSE.md
  author: Firas Midani
  author_email: fsm.promotions@gmail.com

extra:
  maintainers:
    - Firas Midani
  identifiers:
    - doi:10.1128/mSystems.00508-21
