#!/bin/bash

# __author__ = Firas S Midani
# __email__ = midani@bcm.edu

# Midani et al. (2020) Figure 1C-D uses data generated by this script 

# load amiga source environment
source $1

# create variable for the absolute file path to amiga.py
amiga=$2

# fit each individual growth curve
python $amiga/amiga.py fit \
	-i $amiga/examples/manuscript/death/ \
	-o CD2058_Low_Glucose_split \
	-s 'Isolate:CD2058;Substrate:Glucose;Concentration:Low' \
	--verbose --save-gp-data --save-cleaned-data

# pool replicates then fit
python $amiga/amiga.py fit \
	-i $amiga/examples/manuscript/death/ \
	-o CD2058_Low_Glucose_pooled \
	-s 'Isolate:CD2058;Substrate:Glucose;Concentration:Low' \
	--verbose --save-gp-data --save-cleaned-data \
	--pool-by 'Isolate'