#!/bin/bash

# __author__ = Firas Said Midani
# __email__ = midani@bcm.edu

# Midani et al. (2021) Supp. Figure 5 and 7 uses data generated by this script 

# Objective
#
# The main illustrations for AMiGA are based on growth data of Clostridioides difficile.
# Here, we aimed to illustrate that AMiGA is not limited to growth curves of C. difficile.
# So, we take advantage of several publicly available growth curve data to showcase the 
# utility of AMiGA. In particular, we use the following data sets:
#
# Cuevas DA and Edwards RA.
# PMAnalyzer: a new web interface for bacterial growth curve analysis.  
# Bioinformatics (2017)
#
# Dunphy LJ, Yan P, and Papin JA.
# Integrated experimental and computational analyses reveal differential metabolic
# functionality in antibiotic-resistant Pseudomonas aeruginosa.
# Cell Systems (2019)
#
# Vervier K, Browne, HP, and Lawley TD.
# CarboLogR: a Shiny/R application for statistical analysis of bacterial utilisation of carbon sources. 
# bioRxiv (2019)
#
# In this script, we download the data sets corresponding to these articles, format them
# so that AMiGA can parse them, and then process the growth curves with AMiGA. 
# 

#########################################
# Point to Python environment and AMiGA #
#########################################

# load amiga source environment
source $1

# create variable for the absolute file path to amiga.py
amiga=$2

# mkdir -p ./non_cdiff/{cuevas,dunphy,vervier}

# #####################################
# # Cuevas 2017: Citrobacter sedlakii #
# #####################################

# Download PMAnalyzer from Github
if [[ ! -e ./non_cdiff/cuevas/PMAnalyzer ]]; then 
    git clone https://github.com/dacuevas/PMAnalyzer.git ./non_cdiff/cuevas/PMAnalyzer
fi

# There are sample data for 3 C. sedlakii isolates. However, only R.S.3_ID952 and R.S.3_ID953 correlate
# well with each other. See ./PMAnalyzer/sample_results/log_R.S.3.png. So, I will only analyze those two isolates.

# These PM plates include both carbon and nitrogen sources. For the analysis, we will exclude the nitrogen
# sources, which would allow for fairer comparison to the other projects (dunphy and vervier)

# first, read sample data and prepare for AMiGA
python ./scripts_analysis/py/format_cuevas_files.py

# set up parameters for AMiGA processing
interval=1800
working="./non_cdiff/cuevas/working"

# basic summary
python $amiga/amiga.py summarize -i $working --verbose

# fit each curve separately
python $amiga/amiga.py fit \
    -i $working \
    -o cuevas_split --merge-summary \
    -s "Plate_ID:R.S.3_ID952,R.S.3_ID953;Source_Type:Carbon" \
    -t $interval \
    --plot --plot-derivative \
    --save-gp-data --save-cleaned-data --verbose

# pool then fit curves
timestepsize=1
skipfirstn=0

python $amiga/amiga.py fit \
    -i $working \
    -o cuevas_pooled --merge-summary \
    -s "Plate_ID:R.S.3_ID952,R.S.3_ID953;Source_Type:Carbon" \
    --pool-by "Substrate" --sample-posterior \
    -t $interval -tss $timestepsize -sfn $skipfirstn --keep-missing-time-points \
    --save-gp-data --save-cleaned-data --verbose

# normalize parameters
python $amiga/amiga.py normalize \
    -i $working/summary/cuevas_split_summary.txt \
    --normalize-method "division" --group-by "Plate_ID" --normalize-by "Substrate:Negative Control"

python $amiga/amiga.py normalize \
    -i $working/summary/cuevas_pooled_summary.txt \
    --normalize-method "division" --normalize-by "Substrate:Negative Control"


##############################################
# Dunphy 2019: Psuedomonas aeruginosa BIOLOG #
##############################################

# Download code/data from Github
if [[ ! -e ./non_cdiff/dunphy/supplement ]]; then 
    git clone https://github.com/lauradunphy/dunphy_yen_papin_supplement.git ./non_cdiff/dunphy/supplement
fi

# first, read sample data and prepare for AMiGA
python ./scripts_analysis/py/format_dunphy_files.py

# set up parameters for AMiGA processing
interval=600
working="./non_cdiff/dunphy/working"

# basic summary
python $amiga/amiga.py summarize -i $working --verbose

# fit each curve separately
python $amiga/amiga.py fit \
    -i $working \
    -o dunphy_split --merge-summary \
    -t $interval \
    --subset 'Isolate:Day0Anc;PM:1' \
    --plot --plot-derivative \
    --save-gp-data --save-cleaned-data --verbose

# pool then fit curves
timestepsize=4
skipfirstn=0

python $amiga/amiga.py fit \
    -i $working \
    -o dunphy_pooled --merge-summary \
    --subset 'Isolate:Day0Anc;PM:1' \
    --pool-by "Isolate,PM,Substrate" --sample-posterior \
    -t $interval -tss $timestepsize -sfn $skipfirstn --keep-missing-time-points \
    --save-gp-data --save-cleaned-data --verbose

# normalize parameters
python $amiga/amiga.py normalize \
    -i $working/summary/dunphy_split_summary.txt \
    --normalize-method "division" --group-by "Plate_ID" --normalize-by "Substrate:Negative Control"

python $amiga/amiga.py normalize \
    -i $working/summary/dunphy_pooled_summary.txt \
    --normalize-method "division" --group-by "PM,Isolate" --normalize-by "Substrate:Negative Control"


############################################################
# Dunphy 2019: Psuedomonas aeruginosa N-Acetyl-Glucosamine #
############################################################

# first, read sample data and prepare for AMiGA
python ./scripts_analysis/py/format_dunphy_glcnac_files.py

interval=639
working="./non_cdiff/dunphy/working"
timestepsize=4
skipfirstn=0

# pool then fit curves
python $amiga/amiga.py fit \
    -i $working/data/dunphy_glcnac_mutants.txt \
    -o dunphy_glcnac_mutants_pooled --merge-summary \
    --pool-by "Strain" --sample-posterior \
    -t $interval -tss $timestepsize -sfn $skipfirstn --keep-missing-time-points \
    --save-gp-data --save-cleaned-data --verbose

# hypothesis testing: compare all strains against the ancestor
timestepsize=4

# create an array of all the unique strain names
strains=( $(awk '{print $3}' $working/mapping/dunphy_glcnac_mutants.txt | sort | uniq) )
declare -p strains

# compare all strains against ancestor, except for itself
for strain in "${strains[@]}";
do

	if [[ $strain == 'Ancestor' ]]; then 
		continue
	fi

	python $amiga/amiga.py test \
		-i $working/data/dunphy_glcnac_mutants.txt \
		-o Ancestor_vs_$strain \
		-s 'Strain:Ancestor,'$strain \
		-t $interval -tss $timestepsize -sfn $skipfirstn\
		-y 'H0:Time;H1:Time+Strain' \
		--sample-posterior --confidence 95 -np 99\
		--verbose

done

# hypothesis testing comparing PA14_44360 and PA14_41710

python $amiga/amiga.py test \
	-i $working/data/dunphy_glcnac_mutants.txt \
	-o PA14_44360_vs_PA14_41710 \
	-s 'Strain:PA14_44360,PA14_41710' \
	-t $interval -tss $timestepsize -sfn $skipfirstn\
	-y 'H0:Time;H1:Time+Strain' \
	--sample-posterior --confidence 95 -np 99\
	--verbose


# #########################################
# # Vervier 2017: Yersinia enterocolitica #
# #########################################

# Download CarboLogR from Github
if [[ ! -e ./non_cdiff/vervier/CarboLogR ]]; then 
    git clone https://github.com/kevinVervier/CarboLogR.git ./non_cdiff/vervier/CarboLogR
fi

# first, read sample data and prepare for AMiGA
python ./scripts_analysis/py/format_vervier_files.py

# set up parameters for AMiGA processing
interval=900
working="./non_cdiff/vervier/working"

# basic summary
python $amiga/amiga.py summarize -i $working --verbose

# fit each curve separately
python $amiga/amiga.py fit \
    -i $working \
    -o vervier_split --merge-summary \
    -t $interval \
    --subset 'Isolate:8081c;PM:1' \
    --plot --plot-derivative \
    --save-gp-data --save-cleaned-data --verbose

# pool then fit curves
timestepsize=3
skipfirstn=0

python $amiga/amiga.py fit \
    -i $working \
    -o vervier_pooled --merge-summary \
    --subset 'Isolate:8081c;PM:1' \
    --pool-by "Isolate,PM,Substrate" --sample-posterior \
    -t $interval -tss $timestepsize -sfn $skipfirstn --keep-missing-time-points \
    --save-gp-data --save-cleaned-data --verbose

# normalize parameters
python $amiga/amiga.py normalize \
    -i $working/summary/vervier_split_summary.txt \
    --normalize-method "division" --group-by "Plate_ID" --normalize-by "Substrate:Negative Control"

python $amiga/amiga.py normalize \
    -i $working/summary/vervier_pooled_summary.txt \
    --normalize-method "division" --group-by "PM,Isolate" --normalize-by "Substrate:Negative Control"

